# Generated by Django 3.2.8 on 2021-10-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftedchild',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subs', to='database.GiftedChild'),
        ),
    ]
