# Generated by Django 3.2.8 on 2021-10-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_giftedchild_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=64, null=True)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_level', models.IntegerField()),
                ('bio', models.CharField(blank=True, max_length=512, null=True)),
                ('school', models.CharField(blank=True, max_length=512, null=True)),
                ('organizations', models.CharField(blank=True, max_length=512, null=True)),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('challenge_name', models.CharField(max_length=64)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('req_talent_level', models.IntegerField()),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.talent')),
            ],
        ),
    ]
