# Generated by Django 3.2.8 on 2021-10-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_challenge_talent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='achievement', max_length=64)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('achievement_type', models.CharField(blank=True, default='', max_length=64)),
                ('talent_points', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='users',
            field=models.ManyToManyField(blank=True, to='database.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_name',
            field=models.CharField(default='challenge', max_length=64),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='req_talent_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(default='talent', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='login', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='login', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='task', max_length=64)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('task_points', models.IntegerField(default=0)),
                ('task_number', models.IntegerField(default=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(default='step', max_length=64)),
                ('action', models.CharField(default='action', max_length=64)),
                ('step_number', models.IntegerField(default=1)),
                ('step_text', models.CharField(blank=True, max_length=512, null=True)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('button_text', models.CharField(blank=True, max_length=512, null=True)),
                ('meta_type', models.CharField(blank=True, max_length=64, null=True)),
                ('meta_urls', models.CharField(blank=True, max_length=512, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.task')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='achievement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.achievement'),
            preserve_default=False,
        ),
    ]
